# Generated by Django 6.0.3 on 2026-05-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='min_price_allowed',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
