# Generated by Django 6.0.3 on 2026-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, help_text='Leave blank for loose items', max_length=50, null=True)),
                ('unit_type', models.CharField(choices=[('PC', 'Piece / Item'), ('KG', 'Kilogram (kg)'), ('PK', 'Packet / Bundle'), ('LT', 'Litre (L)')], default='PC', max_length=2)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Use decimals for KG items (e.g., 0.5)', max_digits=10)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
